#!/bin/bash

MESSAGE=$(cat $1)
COMMITFORMAT=$(echo $MESSAGE | grep -E "^(break|build|ci|docs|feat|fix|perf|refactor|style|test|chore)\([a-z0-9-]{1,50}\)?:( [A-Z][A-Z0-9]{1,9}-[1-9][0-9]{0,4}){1,10}\s[A-Z][A-Za-z0-9., ]{2,49}$")
if [[ "$COMMITFORMAT" == "" ]]; then
  echo "Your commit was rejected due to the commit message. Skipping..."
  echo ""
  echo "Please use the following format sample:"
  echo "feat(login): APP-123 APP-456 New login flow"
  echo ""
  echo "More details please read the document on: https://docs.google.com/document/d/1bGd6yFez40Fow-IeEGwl5AzMwlCGl47YAa3GW8m6jx4/edit#heading=h.e6padd85yd3e"
  exit 1
fi
